services:
  djangoapp:
    container_name: pigeonapp_django
    build:
      context: .
      dockerfile: django.Dockerfile
    ports:
      - "3000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy

  celery_worker:
    container_name: pigeonapp_celery_worker
    build:
      context: .
      dockerfile: celery.Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  celery_beat:
    container_name: pigeonapp_celery_beat
    build:
      context: .
      dockerfile: celerybeat.Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  db:
    container_name: pigeonapp_db
    image: postgres:12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 1s
      retries: 50
    env_file:
      - .env
    ports:
      - "8432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: pigeonapp_rabbitmq
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl node_health_check"]
      interval: 10s
      timeout: 1s
      retries: 50
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env

volumes:
  pgdata: {}
