# Generated by Django 5.0.6 on 2024-06-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeonwebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker_from',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
